version: "3"
services:
  logservice:
    build:
      context: ./
      dockerfile: Dockerfile
    # docker-compose mounts as root
    user: root
    ports:
      - '8080:8080'
      - '6343:6343/udp'
      - '2055:2055/udp'
    command:
      - -transport=file
      - -transport.file=/var/log/logservice/ldrain.log
      - -format=json
    restart: always
    volumes:
      - logs:/var/log/logservice
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1-amd64
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1-amd64
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.1-amd64
    user: root
    links:
      - elasticsearch
    volumes:
      - ./logstash.conf:/etc/logstash/logstash.conf
      - logs:/var/log/goflow
    command: logstash -f /etc/logstash/logstash.conf
    ports:
      - 12201:12201/udp
    depends_on:
      - elasticsearch
volumes:
  logs:
